doniApi/urls.py
from doniApi import *
from django.conf.urls import include, url

from doniApi.authentication.Login import LoginAPI
from doniApi.authentication.Logout import LogOutAPI
import notifications.urls
import doniInventory.urls
import doniLocalTrade.urls

'''
    All Data API for Doni Group
'''

urlpatterns = (
    url('^inventory/', include(doniInventory.urls, namespace='inventory')),
    url('^local_trade/', include(doniLocalTrade.urls, namespace='local_trade_book')),
    url('^notifications/', include(notifications.urls, namespace='notifications')),
    url(r"login/$", LoginAPI.as_view(), {"public_api": True}, name="login"),
    url(r"logout/$", LogOutAPI.as_view(), name="logout"),

    url(r"^auth/google_analytics/$", GetGoogleAccessTokenAPI.as_view(), name='Google_Access_Token'),

    url(r'^dashboard/$', MainDashboardAPI.as_view(), name='Main_Dashboard_API'),

    url(r'^dashboard/search_top/$', PageTopSearchAPI.as_view(), name='Page_Top_API'),

    url(r'website/dashboard/$', WebsiteDashboardAPI.as_view(), name='Website_Dashboard_API'),

    url(r'^website/research/display/$', BlogDisplayAPI.as_view(), name='Blogs_API'),

    url(r'^website/research/$', BlogAPI.as_view(), name='Blogs_API'),

    url(r'^website/research/(?P<research_id>[0-9]+)/$', BlogAPI.as_view(), name='Blogs_API'),

    url(r'website/research_tags', BlogTagAPI.as_view(), name='BlogTagAPI'),

    # User Related API

    url(r'^user/changePassword/$',
        ChangePassword.as_view(),
        name='Change_Password'),

    url(r'user/$',
        User.as_view(),
        name='User'),

    url(r'user/(?P<user_id>[0-9]+)/profilePic/$',
        UserProfilePicAPI.as_view(),
        name='User'),

    # Business Partner Related API

    url(r'business/self/$',
        BusinessSettingsAPI.as_view(),
        name='Self_Business'),

    url(r'business/list/$',
        BusinessListAPI.as_view(),
        name='Business List'),

    url(r'business/basic/$',
        BpBasicAPI.as_view(),
        name='Business Partner Basic'),

    url(r'business/basic/(?P<bp_id>[a-zA-Z0-9.@_-]+)/$',
        BpBasicAPI.as_view(),
        name='Business Partner Basic'),

    url('business/location/$',
        BpLocationAPI.as_view(),
        name='Business Location API'),

    url('business/contact_person/$',
        BpContactPersonAPI.as_view(),
        name='Business Contact Person API'),

    url('business/contact_number/$',
        BpContactNumberAPI.as_view(),
        name='Business Contact Number API'),

    url('business/bank/$',
        BpBankAPI.as_view(),
        name='Business Bank API'),

    url('business/report/(?P<bp_id>[a-zA-Z0-9.@_-]+)/$',
        BusinessReportAPI.as_view(),
        name='Business Report API'),

    # Transaction Related API

    url(r'transactions/list/$',
        TransactionListAPI.as_view(),
        name='Transaction List'),

    url(r'transactions/washout/$',
        TransactionWashoutAPI.as_view(),
        name='Transaction Washout'),

    url(r'transactions/completeStatus/$',
        TransactionCompleteStatusAPI.as_view(),
        name='Transaction List'),

    url(r'transactions/shipmentStatus/$',
        TransactionShipmentStatusAPI.as_view(),
        name='Transaction List'),

    url(r'transactions/approbation_received_info/$',
        ShipmentApprobationReceivedInfoAPI.as_view(),
        name='Transaction Approbation Recieved Info'),

    url(r'transactions/arrived_at_port_info/$',
        ShipmentArrivedAtPortInfoAPI.as_view(),
        name='Transaction Arrived Info'),

    url(r'transactions/shipped_info/$',
        ShipmentShippedInfoAPI.as_view(),
        name='Transaction Shipment Info'),

    url(r'transactions/not_shipped_info/$',
        ShipmentNotShippedInfoAPI.as_view(),
        name='Transaction Not Shipped Info'),

    url(r'transactions/basic/$',
        TransactionBasicAPI.as_view(),
        name='Transaction Basic'),

    url(r'transactions/basic/(?P<tr_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionBasicAPI.as_view(),
        name='Transaction Basic'),

    url(r'transactions/note/(?P<tr_id>[a-zA-Z0-9.@_-]+)/(?P<note_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionNoteAPI.as_view(),
        name='Transaction Basic'),

    url(r'transactions/note/$',
        TransactionNoteAPI.as_view(),
        name='Transaction Notes'),

    url(r'transactions/note/(?P<tr_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionNoteAPI.as_view(),
        name='Transaction Notes'),

    url(r'transactions/cash_flow/$',
        TransactionCashFlowAPI.as_view(),
        name='Transaction Cash Flow'),

    url(r'transactions/commission/(?P<tr_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionCommissionAPI.as_view(),
        name='Transaction Commission'),

    url(r'transactions/contract/(?P<tr_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionContractAPI.as_view(),
        name='Transaction Contract'),

    url(r'transactions/document/$',
        TransactionDocumentAPI.as_view(),
        name='Transaction Documents'),



    url(r'transactions/document/(?P<document_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionDocumentAPI.as_view(),
        name='Transaction Documents'),



    url(r'transactions/secondary/(?P<tr_id>[a-zA-Z0-9.@_-]+)/$',
        TransactionSecondaryAPI.as_view(),
        name='Transaction Secondary'),

    url(r'transactions/(?P<tr_id>[a-zA-Z0-9.@_-]+)/status/$',
        TransactionBasicAPI.as_view(),
        name='Transaction Status'),

    url(r'transactions/dashboard/$',
        TransactionDashboardAPI.as_view(),
        name='Transaction Dashboard API'),

    url(r'transactions/businessAnalytics/$',
        TransactionBusinessAnalyticsAPI.as_view(),
        name='Transaction Dashboard API'),

    url(r'transactions/dispute/$',
        TransactionDisputeAPI.as_view(),
        name='Transaction DisputeBusinessReportAPI API'),

    url(r'transactions/arrived_not_completed/$',
        TransactionArrivedNotCompletedListAPI.as_view(),
        name='Transaction_Arrived_Not_Completed'),

    # url(r'transactions/(?P<tr_id>[a-zA-Z0-9.@_-]+)/shipment/$',
    #     TransactionShipmentAPI.as_view(),
    #     name='Transaction Shipment'),

    # Reports Related API

    # Manifest Related API

    # Price Market API

    url(r'pricing/price_market/$',
        PricingMarketAPI.as_view(),
        name='Pricing_Market_API'
        ),

    url(r'pricing/product_item/analytics/$',
        PricingAnalyticsAPI.as_view(),
        name='Product Pricing Analytics'),

    # Product Items Pricing API

    url(r'pricing/product_item/$',
        ProductItemPricingAPI.as_view(),
        name='Product_Item_Pricing_API'),

    url(r'pricing/product_item/(?P<product_item_price_id>[0-9]+)/$',
        ProductItemPricingAPI.as_view(),
        name='Product_Item_Pricing_API'),

    url(r'pricing/summary/$',
        PricingSummaryAPI.as_view(),
        name='Price_Summary_API'),

    # Product Pricing API

    url(r'^website/pricing/graph/(?P<product_item_id>[0-9]+)/(?P<start_date>\d{4}-\d{2}-\d{2})/(?P<end_date>\d{4}-\d{2}-\d{2})/$',
        WebsitePricingGraphAPI.as_view(),
        name='Website_Pricing_API'
        ),

    # Shipping API

    url('shipping/port_tag/$',
        ShippingPortTagAPI.as_view(),
        name='Shipping Ports List API'),

    url('shipping/vessel_tag/$',
        VesselTagAPI.as_view(),
        name='Shipping Ports List API'),


    url('shipping/vessel/list/$',
        VesselListAPI.as_view(),
        name='Shipping Ports List API'),

    url('shipping/vessel/$',
        VesselAPI.as_view(),
        name='Shipping Ports API'),

    url('shipping/vessel/(?P<vessel_id>[0-9]+)/$',
        VesselAPI.as_view(),
        name='Shipping Ports API'),


    url('shipping/line/list/$',
        ShippingLineListAPI.as_view(),
        name='Shipping Ports List API'),

    url('shipping/line/$',
        ShippingLineAPI.as_view(),
        name='Shipping Ports API'),

    url('shipping/line/(?P<line_id>[0-9]+)/$',
        ShippingLineAPI.as_view(),
        name='Shipping Ports API'),

    url('shipping/ports/list/$',
        ShippingPortListAPI.as_view(),
        name='Shipping Ports List API'),

    url('shipping/ports/$',
        ShippingPortAPI.as_view(),
        name='Shipping Ports API'),

    url('shipping/ports/(?P<port_id>[0-9]+)/$',
        ShippingPortAPI.as_view(),
        name='Shipping Ports API'),

    # Product Keyword API

    url(r'product/category/$',
        ProductsCategoryAPI.as_view(),
        name='Product_Category_API'),

    url(r'product/category/specification/$',
        ProductSpecificationAPI.as_view(),
        name='Product Specification API'),

    url(r'product/keywords/$',
        ProductsKeywordAPI.as_view(),
        name='Products Keywords API'),

    url(r'product/keywords/(?P<product_id>[0-9]+)/$',
        ProductsKeywordAPI.as_view(),
        name='Products Keywords'),

    url(r'keywords/(?P<keyword_id>[0-9]+)/$',
        ProductsKeywordAPI.as_view(),
        name='Products Keywords'),

    # Product API

    # Product Related API

    url(r'product/$',
        ProductsAPI.as_view(),
        name='Products'),

    url(r'product/product_tags/$',
        ProductTagsAPI.as_view(),
        name='Product_Tags'),

    url(r'product/website_status/$',
        ProductOnWebsiteAPI.as_view(),
        name='Products_Website_Status'),

    url(r'product/(?P<product_id>[0-9]+)/$',
        ProductsAPI.as_view(),
        name='Products'),

    url(r'product/origin/$',
        ProducOriginAPI.as_view(),
        name='Products Origins'),

    url(r'^product_item/$',
        ProductItemAPI.as_view(),
        name='Products_Item_API'),

    url(r'^product_item/specs/$',
        ProductItemSpecificationAPI.as_view(),
        name='Product_Specification_API'
        ),

    url(r'^product_item/price_on_website/$',
        ProductItemPriceOnWebsiteAPI.as_view(),
        name='Product_Item_Price_On_Website'),

    url(r'^product_item/price_report/$',
        ProductItemPriceReportAPI.as_view(),
        name='Product_Item_Price_Report'),

doniGroup/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^api/', include('doniApi.urls', namespace='api')),
                  url(r'^grappelli/', include('grappelli.urls')),
                  url(r'^', include("website.urls", namespace='web')),
                  url(r'^markdownx/', include('markdownx.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from api.views import SingleBlog, ProductPage
from api.views import HomePage, BlogPage, SingleProductPage
from api.views import PricingPage, PricingDetail
from api.views import PrivacyPage


urlpatterns = [
    url(r'^$', HomePage.as_view(), name='homePage'),
    url(r'^research/$', BlogPage.as_view(), name='blogs'),
    url(r'^products/$', ProductPage.as_view(), name='products'),
    url(r'^product/$', SingleProductPage.as_view(), name='single_product'),
    url(r'^pricing/$', PricingPage.as_view(), name='pricingPage'),
    url(r'^research/(?P<slug>[\w-]+)/$', SingleBlog.as_view(), name='detail'),
    url(r'^price/analytics/$', PricingDetail.as_view(), name='pricing_detail'),
    url(r'^privacy/$', PrivacyPage.as_view(), name='privacy_policy')

]

website/api/views/blog.py
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from doniApi.apiImports import Response, GenericAPIView, status

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from website.models import Post, Tag
from django.utils import timezone

from website.serializers.single_blog import SingleBlogSerializer
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
    )


class BlogPage(View):
    template_name = 'blog.html'

    def get(self, request, *args, **kwargs):
        tags = Tag.objects.filter(blog__isnull=False).values('name', 'slug').distinct()
        today = timezone.now().date()
        queryset_list = Post.objects.active().order_by("-timestamp")


        query = request.GET.get("q")
        tag = request.GET.get("tag")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)
            ).distinct()
        if tag:
            query_tag = Tag.objects.filter(name=tag)
            queryset_list = Post.objects.filter(tags__in=query_tag).distinct()
        paginator = Paginator(queryset_list, 8)  # Show 25 contacts per page
        page_request_var = "page"
        page = request.GET.get(page_request_var)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        context = {

            "tags": tags,
            "object_list": queryset,
            "title": "List",
            "page_request_var": page_request_var,
            "today": today,
        }
        return render(request, self.template_name, context)


import urllib


class SingleBlog(View):
    template_name = 'post.html'

    def get(self, request, *args, **kwargs):
        slug = kwargs.get('slug')
        instance = get_object_or_404(Post, slug=slug)
        base_url = request.build_absolute_uri()
        if instance.publish > timezone.now().date() or instance.draft:
            if not request.user.is_staff or not request.user.is_superuser:
                raise Http404

        tags = Tag.objects.filter(blog__isnull=False).values('name', 'slug').distinct()
        instance.increment_visitor()
        import re
        share_string = re.sub(r'[^\x00-\x7F]+', ' ', instance.content)
        context = {
            "tags": tags,
            "instance": instance,
            "base_url": base_url,

            "share_string": urllib.pathname2url(share_string),
        }
        return render(request, self.template_name, context)

website/api/views/home.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from website.models import HomeSlider, HomeServices
from doniServer.models import *
from datetime import datetime as dt, time, timedelta

class HomePage(View):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        slides = HomeSlider.objects.all()
        services = HomeServices.objects.all()
        ticker_item, price_date = ProductItem.get_price_ticker()
        context = {
            'ticker_items': ticker_item,
            'price_date': price_date+timedelta(hours=5),
            'slides': slides,
            'services': services
        }
        return render(request, 'home.html', context)

website/api/views/pricing.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from doniServer.models import Products, ProductCategory, ProductItem, PriceSummary
from django.db.models import Max
from datetime import datetime as dt
from datetime import timedelta
from django.conf import settings


class PricingPage(View):
    template_name = 'pricing.html'

    def get(self, request, *args, **kwargs):

        all_product_on_website = ProductItem.objects.filter(price_on_website=True).distinct() \
            .order_by('price_on_website_order')

        price_summary = []

        for item in all_product_on_website:
            price_summary.append(item.price_market_summary)

        context = {
            'priceSummary': price_summary
        }
        return render(request, self.template_name, context)


class PricingDetail(View):
    template_name = 'pricing_details.html'

    def get(self, request, *args, **kwargs):
        now = dt.now()
        year_ago = now - timedelta(days=365)

        product_id = query = request.GET.get("id")
        base_url = request.META.get('HTTP_HOST')
        product_item = ProductItem.objects.get(id=product_id)
        order = product_item.price_on_website_order

        prod_list = ProductItem.objects.filter(price_on_website=True).exclude(id=product_id).distinct() \
            .order_by('price_on_website_order')








        context = {
            'productList': prod_list,
            'priceSummary': product_item.price_market_summary,
            'productItem': product_item,
            'productItemFlagURl': product_item.product_origin.country.flag
        }
        return render(request, self.template_name, context)

website/api/views/privacy.py
from django.views import View
from django.shortcuts import render, get_object_or_404, redirect
from doniServer.models import Products, ProductCategory, ProductItem, PriceSummary
from django.db.models import Max
from datetime import datetime as dt
from datetime import timedelta

class PrivacyPage(View):
    template_name = 'privacy.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template_name, context)

website/templates/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta Data -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Doni & Company</title>
    <meta name="description" content="Agro Commodity Brokerage Firm"/>
    <meta name="keywords"
          content="Tramodity, 'tramodity', Doni, lentils, trade, yellow peas, agriculture, agriculture products, 'desi chickpeas',
          import, export, doni group, doni company, grains, grain, rice, export, import,
          pakistan, karachi, trade, pulses, grain, rice, trading, commodity, commodity brokerage" />

    <meta name="author" content="tramodity"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="shortcut icon" type="image/png" sizes="16x16" href='{% static "img/favicon-16x16.png" %}'>
    <link rel="shortcuticon" type="image/png" sizes="32x32" href='{% static "img/favicon-32x32.png" %}'>
    <link rel="shortcut icon" type="image/png" sizes="96x96" href='{% static "img/favicon-96x96.png" %}'>
    <!--<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">-->

    <!-- Stlylesheet -->
    <link href='{% static "css/style.css" %}' rel="stylesheet" type="text/css" />
    <link href='{% static "css/font-awesome.min.css" %}' rel="stylesheet" type="text/css" />
    <!-- Skin Color -->
    <link rel="stylesheet" href='{% static "css/colors/red.css" %}' id="color-skins"/>


    {% block extrastyles %}

    {% endblock %}

</head>

<!-- start Mixpanel -->
<script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("8f31386937d6654031d0c5d689f08d4e");</script>
<!-- end Mixpanel -->
<body>
{% block afterBodyJS %}
{% endblock %}
<!-- Start Preloader -->
<div id="preloader">
    <div class="loader">
        <img src='{% static "img/assets/doni_and_company.png" %}' alt="Doni & Company">
    </div>
</div>
<!-- End Preloader -->


<header>
    <!-- Start Header -->

    <nav class="navbar navbar-default navbar-alt navbar-small" role="navigation">
        <div class="container">

            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand to-top" rel="home" href="#">
                    <img src='{% static "img/assets/doni_and_company_white.png" %}' alt="Doni & Company" class="logo-big hidden-xs">
                    <img src='{% static "img/assets/logo-dark.png" %}' alt="Doni & Company" class="logo-small">
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="main-nav">
                <ul class="nav navbar-nav  navbar-right">
                    <li><a href='{% url "web:homePage" %}' class="{% if active_tab == 'home' %} active{% endif %}">Home</a></li>
                    <li class="to-section"><a href='{% url "web:homePage" %}#about' >About Us</a></li>
                    <li class="to-section"><a href='{% url "web:products" %}'>Products</a></li>
                    <li class="dropdown">
                                <span class="dropdown-toggle" data-toggle="dropdown">Pricing <b class="caret"></b></span>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href='{% url "web:pricingPage" %}'>Market Summary</a></li>
                                    <li><a href="{% url 'web:pricing_detail' %}?id=10">Price Charts</a></li>

                                </ul>
                    </li>
                    <li><a href='{% url "web:blogs" %}' class="active">Research</a></li>
                    <li class="to-section"><a href='{% url "web:homePage" %}#contact'>Contact</a></li>
                    <li><a class="social-icon" href="https://twitter.com/DoniCompany" target="_blank"><i class="icon icon-social-twitter"></i></a></li>
                    <li><a class="social-icon" href="https://facebook.com/DoniGroup/" target="_blank" href="#"><i class="icon icon-social-facebook"></i></a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

</header>

{% block marquee %}

{% endblock %}


{% block content %}{% endblock content %}



<script src="http://twitter.com/javascripts/blogger.js" type="text/javascript"></script>
<script src="http://api.twitter.com/1/statuses/user_timeline.json?screen_name=DoniCompany&include_rts=true&count=10&callback=twitterCallback2" type="text/javascript"></script>
<!-- jQuery -->
<script src='{% static "js/plugins/jquery.min.js" %}'></script>
<script src='{% static "js/plugins/moderniz.min.js" %}'></script>
<script src='{% static "js/plugins/smoothscroll.min.js" %}'></script>
<script src='{% static "js/plugins/revslider.min.js" %}'></script>
<script src='{% static "js/plugins/bootstrap.min.js" %}'></script>
<script src='{% static "js/plugins/waypoints.min.js" %}'></script>
<script src='{% static "js/plugins/parallax.min.js" %}'></script>
<script src='{% static "js/plugins/easign1.3.min.js" %}'></script>
<script src='{% static "js/plugins/cubeportfolio.min.js" %}'></script>
<script src='{% static "js/plugins/owlcarousel.min.js" %}'></script>
<script src='{% static "js/plugins/tweetie.min.js" %}'></script>
<script src='http://maps.googleapis.com/maps/api/js?key=AIzaSyChOXTm0jxXRYtpOTvPES1N816fVDonXQQ&sensor=false&libraries=places'></script>
<script src='{% static "js/plugins/gmap3.min.js" %}'></script>
<script src='{% static "js/plugins/wow.min.js" %}'></script>
<script src='{% static "js/plugins/counterup.min.js" %}'></script>
<script src='{% static "js/plugins/jquery.marquee.min.js" %}'></script>
<script src='{% static "js/jquery.pause.js" %}'></script>
<script src='{% static "js/scripts.js" %}'></script>

{% block extrajs %}
{% endblock %}

{% if GOOGLE_ANALYTICS_PROPERTY_ID %}
  {% include "ga.html" %}
{% endif %}






</body>
</html>

website/templates/blog_sidebar.html
<div class="col-lg-4 blog-sidebar">
                        <div class="blog-widget-container">
                            <h4></h4>
                            <form method='GET' action='' >
                                <div class="input-group">

                                    <input type="text" class="form-control search" name='q' value='{{ request.GET.q }}' placeholder="Search Blog">
                                    <span class="input-group-btn">
                                        <button class="btn search-button" type="button" type="submit">
                                            <span class="ion-search"></span>
                                        </button>
                                    </span>

                                </div>
                            </form>
                        </div>

                        <div class="blog-widget-container">

                            <h4 class="uppercase">Tags</h4>
                            <ul class="tags-list">
                                {% for tag in tags %}
                                    <li><a href='{% url "web:blogs" %}?tag={{ tag.name }}'>{{ tag.name }}</a></li>
                                {% endfor %}
                                {% if tags|length == 0 %}
                                    <li style="border: none;"> No active tags</li>
                                {% endif %}
                            </ul>

                        </div>

                        <div class="blog-widget-container">
                            <div class="fb-page" data-href="https://www.facebook.com/DoniGroup"
                                 data-tabs="timeline" data-height="500" data-small-header="true"
                                 data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="true">
                                <blockquote cite="https://www.facebook.com/DoniGroup" class="fb-xfbml-parse-ignore">
                                    <a href="https://www.facebook.com/DoniGroup">Doni and Company</a>
                                </blockquote>
                            </div>
                        </div>

                        <div class="blog-widget-container">

                            <h4 class="uppercase">Archives</h4>
                            <ul class="blog-list">
                                <li><a href="#">April 2014</a></li>
                                <li><a href="#">June 2014</a></li>
                                <li><a href="#">September 2014</a></li>
                                <li><a href="#">March 2014</a></li>
                                <li><a href="#">November 2014</a></li>
                            </ul>

                        </div>



                    </div>